#### Goal
The idea in this nb is to identify a list of columns that can be used as target variables, for building our later model, and to also create dummy cols for the categorial vars (e.g. stance being the most obvious one). 
There is one important consideration re splitting the data, in that, if we wanted to predict the win of either side, we'd need to do an additional split of the data. 
OR!! If we wanted to have double the amount of data!!!! we could split by fighter and have an additional row for each one with the fight stats for each one. This way we would be able to do a better prediction of individual fighter behaviour!!!!


Additional note: we actually have the vars for how much the opponent struck the R/B. Arguably we could just drop all those columns.

In [97]:
import pandas as pd
import numpy as np
import statsmodels.stats as sms
import seaborn as sns
import matplotlib.pyplot as plt
import time
import scipy.stats as stats
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_validate
sns.set_style('darkgrid')
# %load_ext autoreload
# %autoreload 2

# df = pd.read_pickle('ufc_total_saved.pkl')

opp_cols=[]
for c in df.columns:
    if c[6:9]=='opp':
        opp_cols.append(c)
        
        
opp_cols

df2 = df.drop(columns=opp_cols)

# first we gotta make a dummy var for winner. 1 if red wins, 0 if blue
df2.Winner.astype('category')
win_result = pd.get_dummies(df2.Winner)
win_result.head()
# df2.drop(columns=['Winner'], inplace=True)
df3 = df2.join(win_result)
# df3.drop(columns=['Red'], inplace=True)
Bcols=[]
Rcols=[]

for c in df2.columns:
    if c[0:2] =='B_':
        Bcols.append(c)
    elif c[0:2] =='R_':
        Rcols.append(c)
        
Bdf = df3.drop(columns=Rcols)
Rdf = df3.drop(columns=Bcols)

def change_col_name(df, pref):
    cols_to_drop=[]
    for col in df.columns:
        if col[0:2]==pref:
            cols_to_drop.append(col)
            new_col = col[2:]
            df[new_col] = df[col]
            
    df.drop(columns = cols_to_drop, inplace=True)
    return df

change_col_name(Bdf, "B_")
change_col_name(Rdf, "R_")

mdf = pd.concat([Rdf, Bdf], axis=0)

In [155]:
mdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10292 entries, 0 to 5145
Data columns (total 61 columns):
newindex                      10292 non-null object
Referee                       10246 non-null object
date                          10292 non-null datetime64[ns]
location                      10292 non-null object
title_bout                    10292 non-null bool
weight_class                  10292 non-null object
no_of_rounds                  10292 non-null int64
last_round                    10292 non-null int64
last_round_time               10292 non-null object
Format                        10292 non-null object
Fight_type                    10292 non-null object
TIME                          10292 non-null timedelta64[ns]
TIMEmod                       10292 non-null int64
Draw                          10292 non-null uint8
Red                           10292 non-null uint8
fighter                       10292 non-null object
current_lose_streak           10292 non-null float64
current_win_streak            10292 non-null float64
draw                          10292 non-null float64
avg_BODY_att                  8375 non-null float64
avg_BODY_landed               8375 non-null float64
avg_CLINCH_att                8375 non-null float64
avg_CLINCH_landed             8375 non-null float64
avg_DISTANCE_att              8375 non-null float64
avg_DISTANCE_landed           8375 non-null float64
avg_GROUND_att                8375 non-null float64
avg_GROUND_landed             8375 non-null float64
avg_HEAD_att                  8375 non-null float64
avg_HEAD_landed               8375 non-null float64
avg_KD                        8375 non-null float64
avg_LEG_att                   8375 non-null float64
avg_LEG_landed                8375 non-null float64
avg_PASS                      8375 non-null float64
avg_REV                       8375 non-null float64
avg_SIG_STR_att               8375 non-null float64
avg_SIG_STR_landed            8375 non-null float64
avg_SIG_STR_pct               8375 non-null float64
avg_SUB_ATT                   8375 non-null float64
avg_TD_att                    8375 non-null float64
avg_TD_landed                 8375 non-null float64
avg_TD_pct                    8375 non-null float64
avg_TOTAL_STR_att             8375 non-null float64
avg_TOTAL_STR_landed          8375 non-null float64
longest_win_streak            10292 non-null float64
losses                        10292 non-null float64
total_rounds_fought           10292 non-null float64
total_time_fought(seconds)    8375 non-null float64
total_title_bouts             10292 non-null float64
win_by_Decision_Majority      10292 non-null float64
win_by_Decision_Split         10292 non-null float64
win_by_Decision_Unanimous     10292 non-null float64
win_by_KO/TKO                 10292 non-null float64
win_by_Submission             10292 non-null float64
win_by_TKO_Doctor_Stoppage    10292 non-null float64
wins                          10292 non-null float64
Stance                        10292 non-null object
Height_cms                    10292 non-null float64
Reach_cms                     10292 non-null float64
Weight_lbs                    10283 non-null float64
age                           10054 non-null float64
Weight_cms                    9 non-null float64
dtypes: bool(1), datetime64[ns](1), float64(44), int64(3), object(9), timedelta64[ns](1), uint8(2)
memory usage: 5.0+ MB

In [102]:
mdf.fighter.value_counts()[200:250]

Andre Fili               12
Matt Lindland            12
Efrain Escudero          12
Myles Jury               12
Felipe Arantes           12
Scott Jorgensen          12
Michael Chiesa           12
Thiago Silva             12
Gegard Mousasi           12
Anthony Perosh           12
Louis Smolka             12
Sam Sicilia              12
Gunnar Nelson            12
Rogerio Nogueira         12
Anthony Smith            12
Pat Barry                12
Alan Jouban              12
Hector Lombard           12
Mark Coleman             12
Jimi Manuwa              12
Vladimir Matyushenko     12
Sean Sherk               12
Wanderlei Silva          12
Kyle Noke                12
Drew Dober               12
Walt Harris              12
James Vick               12
Paul Felder              12
Joanna Jedrzejczyk       12
Jessica Eye              11
Fabio Maldonado          11
Zak Cummings             11
Olivier Aubin-Mercier    11
Ricardo Almeida          11
Gilbert Burns            11
Francisco Rivera         11
Henry Cejudo             11
George Sotiropoulos      11
Ben Rothwell             11
Elias Theodorou          11
Jake Matthews            11
Charlie Brenneman        11
Conor McGregor           11
Hermes Franca            11
Yoel Romero              11
Dan Hooker               11
Vicente Luque            11
Keita Nakamura           11
Nordine Taleb            11
Amanda Nunes             11
Name: fighter, dtype: int64

In [156]:
len(Bdf) + len(Rdf)

10292

In [157]:
len(mdf)

10292

In [158]:
len(mdf.columns)

61

In [106]:
for c in mdf.columns: print(c)

newindex
Referee
date
location
Winner
title_bout
weight_class
no_of_rounds
last_round
last_round_time
Format
Fight_type
time_so_far
round_time_delta
TIME
TIMEmod
Blue
Draw
Red
fighter
current_lose_streak
current_win_streak
draw
avg_BODY_att
avg_BODY_landed
avg_CLINCH_att
avg_CLINCH_landed
avg_DISTANCE_att
avg_DISTANCE_landed
avg_GROUND_att
avg_GROUND_landed
avg_HEAD_att
avg_HEAD_landed
avg_KD
avg_LEG_att
avg_LEG_landed
avg_PASS
avg_REV
avg_SIG_STR_att
avg_SIG_STR_landed
avg_SIG_STR_pct
avg_SUB_ATT
avg_TD_att
avg_TD_landed
avg_TD_pct
avg_TOTAL_STR_att
avg_TOTAL_STR_landed
longest_win_streak
losses
total_rounds_fought
total_time_fought(seconds)
total_title_bouts
win_by_Decision_Majority
win_by_Decision_Split
win_by_Decision_Unanimous
win_by_KO/TKO
win_by_Submission
win_by_TKO_Doctor_Stoppage
wins
Stance
Height_cms
Reach_cms
Weight_lbs
age

In [ ]:
#  now, next priorties would be a. identify categorical variables that needs dummying and b. removing the 
# target df from the x df

In [108]:
mdf.head()

,newindex,Referee,date,location,Winner,title_bout,weight_class,no_of_rounds,last_round,last_round_time,...,win_by_Decision_Unanimous,win_by_KO/TKO,win_by_Submission,win_by_TKO_Doctor_Stoppage,wins,Stance,Height_cms,Reach_cms,Weight_lbs,age
0,Aaron PhillipsMatt Hobar2014-08-23,Kevin Nix,2014-08-23,"Tulsa, Oklahoma, USA",Blue,False,Bantamweight,3,3,5:00,...,0.0,0.0,0.0,0.0,0.0,Southpaw,175.26,177.80,135.0,25.0
1,Aaron RileyJoe Brammer2010-05-29,Steve Mazzagatti,2010-05-29,"Las Vegas, Nevada, USA",Red,False,Lightweight,3,3,5:00,...,2.0,0.0,0.0,0.0,2.0,Southpaw,172.72,175.26,155.0,29.0
2,Aaron RileyJorge Gurgel2008-11-15,Mario Yamasaki,2008-11-15,"Las Vegas, Nevada, USA",Red,False,Lightweight,3,3,5:00,...,0.0,0.0,0.0,0.0,0.0,Southpaw,172.72,175.26,155.0,27.0
3,Aaron RileyJustin Salas2013-07-27,Randy Corley,2013-07-27,"Seattle, Washington, USA",Blue,False,Lightweight,3,3,5:00,...,3.0,0.0,0.0,0.0,3.0,Southpaw,172.72,175.26,155.0,32.0
4,Aaron RileyShane Nelson2009-08-08,Kevin Mulhall,2009-08-08,"Philadelphia, Pennsylvania, USA",Red,False,Lightweight,3,3,5:00,...,1.0,0.0,0.0,0.0,1.0,Southpaw,172.72,175.26,155.0,28.0

In [113]:
mdf.drop(columns=['Winner', 'time_so_far', 'round_time_delta', 'Blue'],inplace=True)

In [114]:
mdf.head()

,newindex,Referee,date,location,title_bout,weight_class,no_of_rounds,last_round,last_round_time,Format,...,win_by_Decision_Unanimous,win_by_KO/TKO,win_by_Submission,win_by_TKO_Doctor_Stoppage,wins,Stance,Height_cms,Reach_cms,Weight_lbs,age
0,Aaron PhillipsMatt Hobar2014-08-23,Kevin Nix,2014-08-23,"Tulsa, Oklahoma, USA",False,Bantamweight,3,3,5:00,3 Rnd (5-5-5),...,0.0,0.0,0.0,0.0,0.0,Southpaw,175.26,177.80,135.0,25.0
1,Aaron RileyJoe Brammer2010-05-29,Steve Mazzagatti,2010-05-29,"Las Vegas, Nevada, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,2.0,0.0,0.0,0.0,2.0,Southpaw,172.72,175.26,155.0,29.0
2,Aaron RileyJorge Gurgel2008-11-15,Mario Yamasaki,2008-11-15,"Las Vegas, Nevada, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,0.0,0.0,0.0,0.0,0.0,Southpaw,172.72,175.26,155.0,27.0
3,Aaron RileyJustin Salas2013-07-27,Randy Corley,2013-07-27,"Seattle, Washington, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,3.0,0.0,0.0,0.0,3.0,Southpaw,172.72,175.26,155.0,32.0
4,Aaron RileyShane Nelson2009-08-08,Kevin Mulhall,2009-08-08,"Philadelphia, Pennsylvania, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,1.0,0.0,0.0,0.0,1.0,Southpaw,172.72,175.26,155.0,28.0

In [116]:
mdf.Stance.value_counts()

Orthodox       7638
Southpaw       2013
Switch          318
Open Stance      24
Sideways          6
Name: Stance, dtype: int64

In [127]:
mdf.loc[mdf.Stance.isna(), 'Stance'] = 'Orthodox'

In [128]:
mdf.loc[mdf.Stance.isna()]

Empty DataFrame
Columns: [newindex, Referee, date, location, title_bout, weight_class, no_of_rounds, last_round, last_round_time, Format, Fight_type, TIME, TIMEmod, Draw, Red, fighter, current_lose_streak, current_win_streak, draw, avg_BODY_att, avg_BODY_landed, avg_CLINCH_att, avg_CLINCH_landed, avg_DISTANCE_att, avg_DISTANCE_landed, avg_GROUND_att, avg_GROUND_landed, avg_HEAD_att, avg_HEAD_landed, avg_KD, avg_LEG_att, avg_LEG_landed, avg_PASS, avg_REV, avg_SIG_STR_att, avg_SIG_STR_landed, avg_SIG_STR_pct, avg_SUB_ATT, avg_TD_att, avg_TD_landed, avg_TD_pct, avg_TOTAL_STR_att, avg_TOTAL_STR_landed, longest_win_streak, losses, total_rounds_fought, total_time_fought(seconds), total_title_bouts, win_by_Decision_Majority, win_by_Decision_Split, win_by_Decision_Unanimous, win_by_KO/TKO, win_by_Submission, win_by_TKO_Doctor_Stoppage, wins, Stance, Height_cms, Reach_cms, Weight_lbs, age]
Index: []

[0 rows x 60 columns]

In [129]:
mdf.Stance.astype('category')

0       Southpaw
1       Southpaw
2       Southpaw
3       Southpaw
4       Southpaw
          ...
5141    Orthodox
5142    Orthodox
5143    Orthodox
5144    Orthodox
5145    Orthodox
Name: Stance, Length: 10292, dtype: category
Categories (5, object): [Open Stance, Orthodox, Sideways, Southpaw, Switch]

In [130]:
stance = pd.get_dummies(mdf.Stance, prefix='stance_')

In [131]:
stance.tail()

,stance__Open Stance,stance__Orthodox,stance__Sideways,stance__Southpaw,stance__Switch
5141,0,1,0,0,0
5142,0,1,0,0,0
5143,0,1,0,0,0
5144,0,1,0,0,0
5145,0,1,0,0,0

In [132]:
mdf.columns

Index(['newindex', 'Referee', 'date', 'location', 'title_bout', 'weight_class',
       'no_of_rounds', 'last_round', 'last_round_time', 'Format', 'Fight_type',
       'TIME', 'TIMEmod', 'Draw', 'Red', 'fighter', 'current_lose_streak',
       'current_win_streak', 'draw', 'avg_BODY_att', 'avg_BODY_landed',
       'avg_CLINCH_att', 'avg_CLINCH_landed', 'avg_DISTANCE_att',
       'avg_DISTANCE_landed', 'avg_GROUND_att', 'avg_GROUND_landed',
       'avg_HEAD_att', 'avg_HEAD_landed', 'avg_KD', 'avg_LEG_att',
       'avg_LEG_landed', 'avg_PASS', 'avg_REV', 'avg_SIG_STR_att',
       'avg_SIG_STR_landed', 'avg_SIG_STR_pct', 'avg_SUB_ATT', 'avg_TD_att',
       'avg_TD_landed', 'avg_TD_pct', 'avg_TOTAL_STR_att',
       'avg_TOTAL_STR_landed', 'longest_win_streak', 'losses',
       'total_rounds_fought', 'total_time_fought(seconds)',
       'total_title_bouts', 'win_by_Decision_Majority',
       'win_by_Decision_Split', 'win_by_Decision_Unanimous', 'win_by_KO/TKO',
       'win_by_Submission', 'win_by_TKO_Doctor_Stoppage', 'wins', 'Stance',
       'Height_cms', 'Reach_cms', 'Weight_lbs', 'age'],
      dtype='object')

In [133]:
mdf.Format.value_counts()

3 Rnd (5-5-5)           9004
5 Rnd (5-5-5-5-5)        846
1 Rnd + OT (12-3)        162
No Time Limit             74
3 Rnd + OT (5-5-5-5)      44
1 Rnd (20)                40
1 Rnd + 2OT (15-3-3)      40
2 Rnd (5-5)               22
1 Rnd (15)                16
1 Rnd (10)                12
1 Rnd (12)                 8
1 Rnd + OT (30-5)          6
1 Rnd + OT (15-3)          4
1 Rnd (18)                 4
1 Rnd + OT (31-5)          2
1 Rnd (30)                 2
1 Rnd + OT (27-3)          2
1 Rnd + OT (30-3)          2
1 Rnd + 2OT (24-3-3)       2
Name: Format, dtype: int64

In [134]:
mdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10292 entries, 0 to 5145
Data columns (total 60 columns):
newindex                      10292 non-null object
Referee                       10246 non-null object
date                          10292 non-null datetime64[ns]
location                      10292 non-null object
title_bout                    10292 non-null bool
weight_class                  10292 non-null object
no_of_rounds                  10292 non-null int64
last_round                    10292 non-null int64
last_round_time               10292 non-null object
Format                        10292 non-null object
Fight_type                    10292 non-null object
TIME                          10292 non-null timedelta64[ns]
TIMEmod                       10292 non-null int64
Draw                          10292 non-null uint8
Red                           10292 non-null uint8
fighter                       10292 non-null object
current_lose_streak           10292 non-null float64
current_win_streak            10292 non-null float64
draw                          10292 non-null float64
avg_BODY_att                  8375 non-null float64
avg_BODY_landed               8375 non-null float64
avg_CLINCH_att                8375 non-null float64
avg_CLINCH_landed             8375 non-null float64
avg_DISTANCE_att              8375 non-null float64
avg_DISTANCE_landed           8375 non-null float64
avg_GROUND_att                8375 non-null float64
avg_GROUND_landed             8375 non-null float64
avg_HEAD_att                  8375 non-null float64
avg_HEAD_landed               8375 non-null float64
avg_KD                        8375 non-null float64
avg_LEG_att                   8375 non-null float64
avg_LEG_landed                8375 non-null float64
avg_PASS                      8375 non-null float64
avg_REV                       8375 non-null float64
avg_SIG_STR_att               8375 non-null float64
avg_SIG_STR_landed            8375 non-null float64
avg_SIG_STR_pct               8375 non-null float64
avg_SUB_ATT                   8375 non-null float64
avg_TD_att                    8375 non-null float64
avg_TD_landed                 8375 non-null float64
avg_TD_pct                    8375 non-null float64
avg_TOTAL_STR_att             8375 non-null float64
avg_TOTAL_STR_landed          8375 non-null float64
longest_win_streak            10292 non-null float64
losses                        10292 non-null float64
total_rounds_fought           10292 non-null float64
total_time_fought(seconds)    8375 non-null float64
total_title_bouts             10292 non-null float64
win_by_Decision_Majority      10292 non-null float64
win_by_Decision_Split         10292 non-null float64
win_by_Decision_Unanimous     10292 non-null float64
win_by_KO/TKO                 10292 non-null float64
win_by_Submission             10292 non-null float64
win_by_TKO_Doctor_Stoppage    10292 non-null float64
wins                          10292 non-null float64
Stance                        10292 non-null object
Height_cms                    10280 non-null float64
Reach_cms                     9306 non-null float64
Weight_lbs                    10283 non-null float64
age                           10054 non-null float64
dtypes: bool(1), datetime64[ns](1), float64(43), int64(3), object(9), timedelta64[ns](1), uint8(2)
memory usage: 4.9+ MB

In [135]:
mdf.Height_cms.mean()

179.25926459143972

In [136]:
mdf.Height_cms.median()

180.34

In [137]:
mdf.Reach_cms.mean()

183.48238340855363

In [138]:
mdf.Reach_cms.median()

182.88

In [143]:
mdf.Weight_lbs.mean()
mdf.Weight_lbs.median()

170.0

In [144]:
mdf.loc[mdf.Height_cms.isna(), "Height_cms"] = mdf.Height_cms.mean() 
mdf.loc[mdf.Reach_cms.isna(), 'Reach_cms'] = mdf.Reach_cms.mean()
mdf.loc[mdf.Weight_lbs.isna(), 'Weight_cms'] = mdf.Weight_lbs.median()

In [145]:
mdf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10292 entries, 0 to 5145
Data columns (total 61 columns):
newindex                      10292 non-null object
Referee                       10246 non-null object
date                          10292 non-null datetime64[ns]
location                      10292 non-null object
title_bout                    10292 non-null bool
weight_class                  10292 non-null object
no_of_rounds                  10292 non-null int64
last_round                    10292 non-null int64
last_round_time               10292 non-null object
Format                        10292 non-null object
Fight_type                    10292 non-null object
TIME                          10292 non-null timedelta64[ns]
TIMEmod                       10292 non-null int64
Draw                          10292 non-null uint8
Red                           10292 non-null uint8
fighter                       10292 non-null object
current_lose_streak           10292 non-null float64
current_win_streak            10292 non-null float64
draw                          10292 non-null float64
avg_BODY_att                  8375 non-null float64
avg_BODY_landed               8375 non-null float64
avg_CLINCH_att                8375 non-null float64
avg_CLINCH_landed             8375 non-null float64
avg_DISTANCE_att              8375 non-null float64
avg_DISTANCE_landed           8375 non-null float64
avg_GROUND_att                8375 non-null float64
avg_GROUND_landed             8375 non-null float64
avg_HEAD_att                  8375 non-null float64
avg_HEAD_landed               8375 non-null float64
avg_KD                        8375 non-null float64
avg_LEG_att                   8375 non-null float64
avg_LEG_landed                8375 non-null float64
avg_PASS                      8375 non-null float64
avg_REV                       8375 non-null float64
avg_SIG_STR_att               8375 non-null float64
avg_SIG_STR_landed            8375 non-null float64
avg_SIG_STR_pct               8375 non-null float64
avg_SUB_ATT                   8375 non-null float64
avg_TD_att                    8375 non-null float64
avg_TD_landed                 8375 non-null float64
avg_TD_pct                    8375 non-null float64
avg_TOTAL_STR_att             8375 non-null float64
avg_TOTAL_STR_landed          8375 non-null float64
longest_win_streak            10292 non-null float64
losses                        10292 non-null float64
total_rounds_fought           10292 non-null float64
total_time_fought(seconds)    8375 non-null float64
total_title_bouts             10292 non-null float64
win_by_Decision_Majority      10292 non-null float64
win_by_Decision_Split         10292 non-null float64
win_by_Decision_Unanimous     10292 non-null float64
win_by_KO/TKO                 10292 non-null float64
win_by_Submission             10292 non-null float64
win_by_TKO_Doctor_Stoppage    10292 non-null float64
wins                          10292 non-null float64
Stance                        10292 non-null object
Height_cms                    10292 non-null float64
Reach_cms                     10292 non-null float64
Weight_lbs                    10283 non-null float64
age                           10054 non-null float64
Weight_cms                    9 non-null float64
dtypes: bool(1), datetime64[ns](1), float64(44), int64(3), object(9), timedelta64[ns](1), uint8(2)
memory usage: 5.0+ MB

In [159]:
mdf.drop(columns=['Stance'])
mdf2 = pd.concat([mdf, stance], axis=1)

In [160]:
mdf2.head()

,newindex,Referee,date,location,title_bout,weight_class,no_of_rounds,last_round,last_round_time,Format,...,Height_cms,Reach_cms,Weight_lbs,age,Weight_cms,stance__Open Stance,stance__Orthodox,stance__Sideways,stance__Southpaw,stance__Switch
0,Aaron PhillipsMatt Hobar2014-08-23,Kevin Nix,2014-08-23,"Tulsa, Oklahoma, USA",False,Bantamweight,3,3,5:00,3 Rnd (5-5-5),...,175.26,177.80,135.0,25.0,NaN,0,0,0,1,0
1,Aaron RileyJoe Brammer2010-05-29,Steve Mazzagatti,2010-05-29,"Las Vegas, Nevada, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,29.0,NaN,0,0,0,1,0
2,Aaron RileyJorge Gurgel2008-11-15,Mario Yamasaki,2008-11-15,"Las Vegas, Nevada, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,27.0,NaN,0,0,0,1,0
3,Aaron RileyJustin Salas2013-07-27,Randy Corley,2013-07-27,"Seattle, Washington, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,32.0,NaN,0,0,0,1,0
4,Aaron RileyShane Nelson2009-08-08,Kevin Mulhall,2009-08-08,"Philadelphia, Pennsylvania, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,28.0,NaN,0,0,0,1,0

In [161]:
mdf_write = pd.to_pickle(mdf2, 'ufc_mdf.pkl')

In [162]:
mdft = pd.read_pickle('ufc_mdf.pkl')

In [165]:
mdft.head()

,newindex,Referee,date,location,title_bout,weight_class,no_of_rounds,last_round,last_round_time,Format,...,Height_cms,Reach_cms,Weight_lbs,age,Weight_cms,stance__Open Stance,stance__Orthodox,stance__Sideways,stance__Southpaw,stance__Switch
0,Aaron PhillipsMatt Hobar2014-08-23,Kevin Nix,2014-08-23,"Tulsa, Oklahoma, USA",False,Bantamweight,3,3,5:00,3 Rnd (5-5-5),...,175.26,177.80,135.0,25.0,NaN,0,0,0,1,0
1,Aaron RileyJoe Brammer2010-05-29,Steve Mazzagatti,2010-05-29,"Las Vegas, Nevada, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,29.0,NaN,0,0,0,1,0
2,Aaron RileyJorge Gurgel2008-11-15,Mario Yamasaki,2008-11-15,"Las Vegas, Nevada, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,27.0,NaN,0,0,0,1,0
3,Aaron RileyJustin Salas2013-07-27,Randy Corley,2013-07-27,"Seattle, Washington, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,32.0,NaN,0,0,0,1,0
4,Aaron RileyShane Nelson2009-08-08,Kevin Mulhall,2009-08-08,"Philadelphia, Pennsylvania, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,28.0,NaN,0,0,0,1,0

In [174]:
target_cols = []
train_cols=[]

for c in mdft.columns:
    if c[0:3]=='avg':
        target_cols.append(c)
    elif c[0:4]=='TIME':
        target_cols.append(c)
    else:
        train_cols.append(c)

In [175]:
target_cols

['TIME',
 'TIMEmod',
 'avg_BODY_att',
 'avg_BODY_landed',
 'avg_CLINCH_att',
 'avg_CLINCH_landed',
 'avg_DISTANCE_att',
 'avg_DISTANCE_landed',
 'avg_GROUND_att',
 'avg_GROUND_landed',
 'avg_HEAD_att',
 'avg_HEAD_landed',
 'avg_KD',
 'avg_LEG_att',
 'avg_LEG_landed',
 'avg_PASS',
 'avg_REV',
 'avg_SIG_STR_att',
 'avg_SIG_STR_landed',
 'avg_SIG_STR_pct',
 'avg_SUB_ATT',
 'avg_TD_att',
 'avg_TD_landed',
 'avg_TD_pct',
 'avg_TOTAL_STR_att',
 'avg_TOTAL_STR_landed']

In [176]:
train_cols

['newindex',
 'Referee',
 'date',
 'location',
 'title_bout',
 'weight_class',
 'no_of_rounds',
 'last_round',
 'last_round_time',
 'Format',
 'Fight_type',
 'Draw',
 'Red',
 'fighter',
 'current_lose_streak',
 'current_win_streak',
 'draw',
 'longest_win_streak',
 'losses',
 'total_rounds_fought',
 'total_time_fought(seconds)',
 'total_title_bouts',
 'win_by_Decision_Majority',
 'win_by_Decision_Split',
 'win_by_Decision_Unanimous',
 'win_by_KO/TKO',
 'win_by_Submission',
 'win_by_TKO_Doctor_Stoppage',
 'wins',
 'Stance',
 'Height_cms',
 'Reach_cms',
 'Weight_lbs',
 'age',
 'Weight_cms',
 'stance__Open Stance',
 'stance__Orthodox',
 'stance__Sideways',
 'stance__Southpaw',
 'stance__Switch']

In [177]:
mdft_x_var = mdft.drop(columns=target_cols)

In [178]:
mdft_x_var.head()

,newindex,Referee,date,location,title_bout,weight_class,no_of_rounds,last_round,last_round_time,Format,...,Height_cms,Reach_cms,Weight_lbs,age,Weight_cms,stance__Open Stance,stance__Orthodox,stance__Sideways,stance__Southpaw,stance__Switch
0,Aaron PhillipsMatt Hobar2014-08-23,Kevin Nix,2014-08-23,"Tulsa, Oklahoma, USA",False,Bantamweight,3,3,5:00,3 Rnd (5-5-5),...,175.26,177.80,135.0,25.0,NaN,0,0,0,1,0
1,Aaron RileyJoe Brammer2010-05-29,Steve Mazzagatti,2010-05-29,"Las Vegas, Nevada, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,29.0,NaN,0,0,0,1,0
2,Aaron RileyJorge Gurgel2008-11-15,Mario Yamasaki,2008-11-15,"Las Vegas, Nevada, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,27.0,NaN,0,0,0,1,0
3,Aaron RileyJustin Salas2013-07-27,Randy Corley,2013-07-27,"Seattle, Washington, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,32.0,NaN,0,0,0,1,0
4,Aaron RileyShane Nelson2009-08-08,Kevin Mulhall,2009-08-08,"Philadelphia, Pennsylvania, USA",False,Lightweight,3,3,5:00,3 Rnd (5-5-5),...,172.72,175.26,155.0,28.0,NaN,0,0,0,1,0

In [179]:
mdft_y_var = mdft.drop(columns=train_cols)

In [180]:
mdft_y_var.head()

,TIME,TIMEmod,avg_BODY_att,avg_BODY_landed,avg_CLINCH_att,avg_CLINCH_landed,avg_DISTANCE_att,avg_DISTANCE_landed,avg_GROUND_att,avg_GROUND_landed,...,avg_REV,avg_SIG_STR_att,avg_SIG_STR_landed,avg_SIG_STR_pct,avg_SUB_ATT,avg_TD_att,avg_TD_landed,avg_TD_pct,avg_TOTAL_STR_att,avg_TOTAL_STR_landed
0,00:15:00,900,14.000000,12.0,6.000,3.000000,26.000000,9.000,8.000000,6.000000,...,1.0,40.0,18.0,0.450000,1.000000,0.000,0.000000,0.000000,137.000000,109.000
1,00:15:00,900,14.333333,11.5,23.000,13.833333,69.166667,21.500,4.333333,3.166667,...,0.0,96.5,38.5,0.381667,0.166667,2.500,0.833333,0.316667,130.833333,70.000
2,00:15:00,900,12.500000,11.0,28.000,15.500000,48.000000,16.000,0.500000,0.500000,...,0.0,76.5,32.0,0.405000,0.500000,3.500,1.000000,0.250000,101.000000,55.000
3,00:15:00,900,13.500000,10.5,19.625,12.375000,68.125000,20.875,3.750000,2.750000,...,0.0,91.5,36.0,0.368750,0.125000,2.875,1.000000,0.283750,127.250000,69.375
4,00:15:00,900,13.250000,11.0,21.250,13.000000,71.500000,26.250,3.250000,2.250000,...,0.0,96.0,41.5,0.422500,0.250000,2.000,0.750000,0.375000,118.000000,61.750

In [181]:
len(mdft_y_var)

10292

In [183]:
len(mdft_x_var)

10292

In [184]:
# now we have all of these vars separated for the regression model. saving as pkl files

pd.to_pickle(mdft_y_var, 'mdf_targets_fight_stats.pkl')
pd.to_pickle(mdft_x_var, 'mdf_input_fight_stats.pkl')